### ISSUE TITLE
Test results explorer doesn't jump to test definition on click

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/vscode-swift#1294]
<kbd> <img width="1904" alt="Screenshot 2024-12-20 at 11 32 50 PM" src="https://github.com/user-attachments/assets/cc759203-eb0e-4d5c-9486-58e1b1d832bb" /> </kbd>

When I (double) click the test name it should jump to the source code definition of the test. Instead it simply does nothing.

**Comment by plemarquand** [comment]
Unfortunately this panel isn't controlled by the Swift Extension; its a core VS Code feature. 

The extension provides vscode.TestItems that have the location/range attached, but it would be to VS Code to jump to the test definition using this information when double clicking a list item in this panel. 

I'm going to close this one out here, but feel free to file an issue in the [VS Code](https://github.com/microsoft/vscode) repo because I do think this would make a good feature.
