### ISSUE TITLE
Failed to setup CodeLLDB for debugging of Swift code

### ISSUE THREAD

**Issue by DeltriDev** [swiftlang/vscode-swift#887]
**Describe the bug**
When I try to run a swift program through vscode (so like, F5) it doesnt work. When I launch vs code, i get this popup message:
`Failed to setup CodeLLDB for debugging of Swift code. Debugging may produce unexpected results. Error: Failed to find LLDB in swift toolchain. (source:Swift)`
For now I just use `swift run` on the terminal to run prokects

**To Reproduce**
1. Install swift
2. Install the swift vscode plugin
3. this happens

**Expected behavior**
I should be able to just run the swift project i guess

**Environment**
 - OS: Windows 10
 - Swift version: 5.10
 - Visual Studio Code version: 1.90.0
 - vscode-swift version: v1.10.1

**Comment by DeltriDev** [comment]
@matthewbastien does that mean it's fixed? How can I test it?

**Comment by adam-fowler** [comment]
@DeltriDev you can either build the extension for yourself or wait for the next release, hopefully not too long. We have build instructions in the CONTRIBUTING.md guide

**Comment by plemarquand** [comment]
I can't verify this because I only have an ARM64 Windows VM and the CodeLLDB extension doesn't support that architecture.

@DeltriDev I updated the CONTRIBUTING.md with a section on [building and installing the extension from the repository](https://github.com/swiftlang/vscode-swift/blob/main/CONTRIBUTING.md#building). Could you try it out to see if this issue is fixed for you?

**Comment by DeltriDev** [comment]
I'll try at some point tomorrow, I'll have to reinstall swift because it caused me some problems and I had to uninstall it

**Comment by DeltriDev** [comment]
@adam-fowler I cannot build so I'll wait for the next update to let you know if it works!

**Comment by award999** [comment]
Verified b461f8f
