### ISSUE TITLE
glob 7.2.3 is deprecated

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/vscode-swift#974]
Warning from `npm install`
```
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```
We didn't allow major updates on glob because it broke the tests. Looks like we can remove this dependency now though

**Comment by plemarquand** [comment]
These warnings are not totally under our control since they get reported even when installing dependencies of our dependencies. For instance we depend on `@vscode/vsce`, [which still depends on glob 7.0.6](https://github.com/microsoft/vscode-vsce/blob/main/package.json#L49). We get a deprecation warning about that.

**Comment by adam-fowler** [comment]
Currently we are referencing "glob": "~7.2.3" in the devDependencies, maybe we should remove it if we aren't using it. It looks like the test code reliant on it has been removed

**Comment by plemarquand** [comment]
Here are a few issues in dependencies we're using that track glob deprecation:
https://github.com/mochajs/mocha/issues/5148
https://github.com/microsoft/vscode-vsce/issues/1026

vscode-test-cli also uses an outdated `c8` that depends on a version of `test-exclude` that uses a deprecated version of `glob`: https://github.com/microsoft/vscode-test-cli/blob/main/package.json
