### ISSUE TITLE
Symbol resolution and intellisense not working

### ISSUE THREAD

**Issue by ptoffy** [swiftlang/vscode-swift#976]
**Describe the bug**
As of a few weeks ago the Swift extension won't show errors/warnings, resolve symbols or any editor related feature. Test discovery  and dependency resolution work

**To Reproduce**
Not really sure, it just stopped working

**Expected behavior**
The aforementioned features should work

**Environment**
 - OS: macOS 14.5
 - Swift version: `swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0`
 - Visual Studio Code version: `1.91.1`
 - vscode-swift version: `1.10.4`

**Additional context**
The diagnostics command spits out these
<img width="1182" alt="Screenshot 2024-07-18 at 23 28 56" src="https://github.com/user-attachments/assets/0593d388-44ca-4500-a0de-4c6350efa74f">
<img width="816" alt="Screenshot 2024-07-18 at 23 30 56" src="https://github.com/user-attachments/assets/03506510-104f-4e5f-a830-816e273fc7ca">

**Comment by plemarquand** [comment]
Hi @ptoffy, thanks for the report.

The line "pending response got rejected since connection got disposed" in the logs indicates to me that [sourcekit-lsp](https://github.com/swiftlang/sourcekit-lsp) crashed on startup.

I see your `swift.sourcekit-lsp.serverArguments` is set to `["-enable-bare-slash-regex"]`. `-enable-bare-slash-regex` is a compiler flag and not a sourcekit-lsp flag, which I think is causing it to crash. Could you try removing this argument from `swift.sourcekit-lsp.serverArguments` and restarting VS Code?

That said, the error reporting here is not great. I've created https://github.com/swiftlang/vscode-swift/issues/979 to track improving this failure message to give a clear report on why sourcekit-lsp failed to launch.

**Comment by ptoffy** [comment]
That seems to have done it! Thanks for spotting that @plemarquand
